version: '3'
services:
  postgres:
    image: postgres:15.5-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./envs/.postgres
    ports:
      - "5432:5432"
  shortener:
    restart: always
    env_file:
      - ./envs/.django
      - ./envs/.postgres
    build: ./
    command: >
      bash ./entrypoint
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data: { }
  postgres_data_backups: { }