#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations
python manage.py migrate
exec /usr/local/bin/gunicorn urlshortener.wsgi --bind 0.0.0.0:8000 --chdir=/urlshortener