# Generated by Django 4.2.7 on 2023-11-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortenedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "modified_time",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                (
                    "slug",
                    models.CharField(max_length=6, unique=True, verbose_name="slug"),
                ),
                ("url", models.URLField(verbose_name="url")),
                (
                    "visitor_count",
                    models.IntegerField(
                        default=0, null=True, verbose_name="visitor_count"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
